import type {Block,Compare,EngineState,Expr,FailureReason,Stage,StepEvent} from './types';
export const num=(value:number):Expr=>({type:'num',value}); export const E:Expr={type:'E'}; export const op=(operator:'+'|'-'|'*',left:Expr,right:Expr):Expr=>({type:'op',op:operator,left,right});
export function evalExpr(expr:Expr,state:EngineState):number{switch(expr.type){case'E':return state.E;case'num':return expr.value;case'op':{const l=evalExpr(expr.left,state),r=evalExpr(expr.right,state);return expr.op==='+'?l+r:expr.op==='-'?l-r:l*r;}}}
export function exprText(expr:Expr):string{switch(expr.type){case'E':return'E';case'num':return String(expr.value);case'op':return`${exprText(expr.left)} ${expr.op==='*'?'×':expr.op} ${exprText(expr.right)}`}}
export function compareText(c:Compare){return{eq:'같다',neq:'같지 않다',gt:'크다',lt:'작다',gte:'크거나 같다',lte:'작거나 같다'}[c]}
function cmp(a:number,c:Compare,b:number){return c==='eq'?a===b:c==='neq'?a!==b:c==='gt'?a>b:c==='lt'?a<b:c==='gte'?a>=b:a<=b}
export function initialState(stage:Stage):EngineState{return{E:0,x:0,y:0,energyLeft:stage.energy,status:'idle',tick:0,message:'편집 가능',events:[],jumps:0,waits:0,usedLines:0,stars:0}}
export function lineCount(blocks:Block[]):number{return blocks.reduce((n,b)=>n+1+(b.type==='condition'?lineCount(b.then)+lineCount(b.else??[]):0),0)}
export function validate(blocks:Block[],depth=0):string[]{const errors:string[]=[]; for(const b of blocks){if(!b.id)errors.push('id 없는 블록'); if(b.type==='move'){if(!b.axis||!b.expr)errors.push('불완전한 이동 블록')}else{if(depth>=2)errors.push('조건 중첩은 최대 2단계입니다'); if(!b.left||!b.right||!b.compare)errors.push('불완전한 조건 블록'); errors.push(...validate(b.then,depth+1),...validate(b.else??[],depth+1));}} return errors}
function tileFailure(stage:Stage,x:number,y:number):FailureReason|undefined{if(x<0||y<0||x>=stage.width||y>=stage.height)return'out-of-bounds'; if(stage.hazards.some(h=>h.x===x&&h.y===y))return'hazard';}
function finishStars(stage:Stage,state:EngineState,blocks:Block[]){state.stars=1+(state.tick<=stage.targetTicks?1:0)+(lineCount(blocks)<=stage.starLineLimit?1:0); state.usedLines=lineCount(blocks)}
function record(state:EngineState,e:StepEvent){state.events.push(e)}
function fail(state:EngineState,reason:FailureReason,blockId:string|undefined,at:{x:number;y:number}){state.status='failed'; state.failureReason=reason; state.message=reason==='out-of-bounds'?'절벽으로 추락했어요.':reason==='hazard'?'위험 타일에 착지했어요.':'에너지가 소진되었어요.'; record(state,{kind:'failure',reason,blockId,at})}
function success(stage:Stage,state:EngineState,blocks:Block[],blockId?:string){state.status='success'; state.message='목표 타일에 정확히 착지했어요!'; finishStars(stage,state,blocks); record(state,{kind:'success',blockId})}
function runBlocks(stage:Stage,blocks:Block[],state:EngineState,root:Block[]){for(const b of blocks){if(state.status==='success'||state.status==='failed')return; state.activeBlockId=b.id; record(state,{kind:'block',blockId:b.id}); if(b.type==='move'){const from={x:state.x,y:state.y}; const v=evalExpr(b.expr,state); const to={x:b.axis==='x'?v:state.x,y:b.axis==='y'?v:state.y}; if(to.x===from.x&&to.y===from.y){state.waits++; record(state,{kind:'wait',blockId:b.id,from,to});}else{state.x=to.x; state.y=to.y; state.jumps++; record(state,{kind:'jump',blockId:b.id,from,to}); const reason=tileFailure(stage,to.x,to.y); if(reason){fail(state,reason,b.id,to); return} if(to.x===stage.goal.x&&to.y===stage.goal.y){success(stage,state,root,b.id); return}}}else{const branch=cmp(evalExpr(b.left,state),b.compare,evalExpr(b.right,state))?'then':'else'; state.activeBranch={blockId:b.id,branch}; record(state,{kind:'branch',blockId:b.id,branch}); runBlocks(stage,branch==='then'?b.then:(b.else??[]),state,root)}}}
export function runTick(stage:Stage,blocks:Block[],prev:EngineState):EngineState{const state:{[K in keyof EngineState]:EngineState[K]}={...prev,events:[],activeBlockId:undefined,activeBranch:undefined,usedLines:lineCount(blocks)}; if(validate(blocks).length){fail(state as EngineState,'incomplete',undefined,{x:state.x,y:state.y});return state as EngineState} if(state.energyLeft<=0){fail(state as EngineState,'energy',undefined,{x:state.x,y:state.y});return state as EngineState} state.status='running'; state.energyLeft-=1; state.E+=1; state.tick+=1; state.message='실행 중'; record(state as EngineState,{kind:'tick-start',tick:state.tick,E:state.E,energy:state.energyLeft}); runBlocks(stage,blocks,state as EngineState,blocks); if(state.status==='running'&&state.energyLeft===0){fail(state as EngineState,'energy',undefined,{x:state.x,y:state.y});} return state as EngineState}
export function runToEnd(stage:Stage,blocks:Block[]):EngineState{let s=initialState(stage); while(s.status!=='success'&&s.status!=='failed')s=runTick(stage,blocks,s); return s}
